version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: pyflink-postgres
    env_file:
      - flink-env.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5632
    ports:
      - '5632:5632'
    expose:
      - '5632'
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./data.dump:/data.dump
      - ./postgres-data:/var/lib/postgresql/data
    command: -p 5632
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-p", "5632", "-U", "postgres"]
  
  # Flink job manager
  jobmanager:
    build:
      context: .
      dockerfile: ./Dockerfile.flink
      platforms:
        - 'linux/amd64'
        - 'linux/arm64'
    image: pyflink-1.18.0
    container_name: pyflink-jobmanager
    pull_policy: never
    platform: 'linux/amd64'
    hostname: 'jobmanager'
    env_file:
      - flink-env.env
    expose:
      - '6123'
    ports:
      - '8081:8081'
    volumes:
      - ./:/opt/flink/usrlib
      - ./keys/:/var/private/ssl/
      - ./src/:/opt/src
    command: jobmanager
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:0.0.0.0'
      - 'host.docker.internal:127.0.0.1'
      - 'host.docker.internal:host-gateway'
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5632/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 3

  # Flink task manager
  taskmanager:
    image: pyflink-1.18.0
    container_name: pyflink-taskmanager
    pull_policy: never
    platform: 'linux/amd64'
    env_file:
      - flink-env.env
    expose:
      - '6121'
      - '6122'
    volumes:
      - ./:/opt/flink/usrlib
      - ./keys/:/var/private/ssl/
      - ./src/:/opt/src
    command: taskmanager --taskmanager.registration.timeout 5 min
    depends_on:
      - jobmanager
    extra_hosts:
      - 'host.docker.internal:0.0.0.0'
      - 'host.docker.internal:127.0.0.1'
      - 'host.docker.internal:host-gateway'
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 15
        parallelism.default: 3

  sql-client:
    image: flink:1.18.1-scala_2.12
    container_name: sql-client
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager

volumes:
  postgres-data:
